name = "my-pageagent"
main = "worker/index.js"
compatibility_date = "2026-05-08"
workers_dev = true
routes = [
  { pattern = "pageagent.space/*", zone_name = "pageagent.space" },
  { pattern = "www.pageagent.space/*", zone_name = "pageagent.space" }
]

[vars]
CREEM_API_BASE = "https://api.creem.io"
CREEM_ENV = "live"

[[d1_databases]]
binding = "DB"
database_name = "openclaw-launch"
database_id = "5c31068a-d85a-4c83-9efe-01e2de1ad22b"

[assets]
directory = "./dist"
binding = "SITE_ASSETS"
not_found_handling = "single-page-application"
run_worker_first = [
  "/*"
]
